### ISSUE TITLE
failed to embed art under windows 10

### ISSUE THREAD

**Issue by ClioCJS** [Martchus/tageditor#103]
Setting tag information for "Zez Confrey - Kitten On The Keys (1921).mp3" ...
 - [100%] Updating ID3v2 tags ...
 - [100%] Preparing streams for rewriting ...
 - [100%] Writing ID3v2 tag ...
 - [100%] Writing MPEG audio frames ...
 - [100%] Writing ID3v1 tag ...
 - Changes have been applied.
 - Diagnostic messages:
    Error        21:23:35   setting tags: Unable set field "Cover": setting field is not supported

fails with both these syntaxes:

```
tageditor set cover=":front-cover" cover0="cover.jpg" -f music.mp3 [i had to edit this example line because i had a typo in it before]
tageditor set cover=":front-cover" cover0="cover.jpg:front-cover:front cover" -f music.mp3

```

The other interesting thing is.. as soon as you're returned to the command prompt afterward, it behaves as if the enter key is held down, except at about 25X the repeat rate. The window has to be terminated as no more commands can be entered at the command line.  

I've been using the TCC lineage of command-lines since the 1980s, they are robust and well developed, and i've never  seen this before.

**Comment by Martchus** [comment]
I have no idea what "TCC lineage" is. Admittedly the syntax I've created and extended over time is a little bit awkward. However, it should be possible to follow the documentation's examples. In your first command the `]` is likely wrong. The second command looks like it should work. I have test cases for this so I'm surprised that it is not working. Maybe the error message you're getting is just about ID3v1 (which would admittedly be a bit confusing and should be improved)?

About the command prompt behavior: I suppose you're using Windows. This platform doesn't allow shipping a GUI and a CLI application nicely as a single binary. I've been working around it but there are caveats, see https://github.com/Martchus/tageditor#windows-specific-issues.

**Comment by ClioCJS** [comment]
TCC, JPSoft's takecommand.
 Over the history of dos/windows machines it's the most-used shell other than command.com / cmd.exe becuase it's been in constant development since the 80s.  Granted, if powershell had been around since the 1980s it would probably have 100X as much use, but it hasn't.
and if cygwin had been around since the 1980s, bash woudly probably end up being used on dos/windows machines more than tcc too, but cygwin didn't really become a thing until the 2000s.

mp3tag actually lets you use CLI options on their GUI binary, but they are useless options - like what folder to open - not useful options like "put this jpg into this mp3".   But yea, i would think the better solution would be to have a separate binary compiled from the exact same code, then it would be easy to extend the same functionality to it maybe?


And oh, for what it's worth, the "]" in my comment above was a typo. Actually, it was me incorrectly removing the %@UNQUOTE[filename] function from my example becuase it muddied up the example.  I've fixed my typo!

**Comment by ClioCJS** [comment]
I managed to capture the errormessage this time, before the runaway infinite scrolling problem. (I think I've seen that once before in my life actually, i've been heavily doing commandline stuff since the 1980s)


**tageditor set cover=":front-cover" cover0="Zez Confrey - Kitten On The Keys (1921).jpg" -f "Zez Confrey - Kitten On The Keys (1921).mp3"**
```

< 9:04a> <4%> C:\b\MISC\1920s\1921\test.copies>Setting tag information for "Zez Confrey - Kitten On The Keys (1921).mp3" ...
 - [100%] Updating ID3v2 tags ...
 - [100%] Preparing streams for rewriting ...
 - [100%] Writing ID3v2 tag ...
 - [100%] Writing MPEG audio frames ...
 - [100%] Writing ID3v1 tag ...
 - Changes have been applied.
 - Diagnostic messages:
    Error        13:04:00   setting tags: Unable set field "Cover": setting field is not supported
```

**Comment by Martchus** [comment]
> i guess they are a "competitor" of yours

Tag Editor is not a commercial product.

>  So there's definitely a way to combine CLI+GUI into one EXE, but why bother?

Please note that I have developed this tool initially for GNU/Linux where this is not a problem at all. Only when trying to use it on Windows later I've noticed that this is problematic.

> I would think the better solution would be to have a separate binary compiled from the exact same code, then it would be easy to share the same functionality so that it runs the exact same code as the GUI, but from the CLIo.

Yes, similar to how I did it later in my other project Syncthing Tray. The only annoyance is that with my current approach of providing a self-contained binary the underlying libraries would be "bundled twice". So maybe I'll also just create a small wrapper for the GUI (like https://github.com/syncthing/syncthing/pull/8760) or tweak my current hack after all (in accordance with https://github.com/syncthing/syncthing/pull/8763 if it ends up successful).

> Also, the runaway problem after it closes? I wonder if perhaps a filehandle is accidentally being left open or something like that.

I don't think that's likely to be the culprit. The culprit is most likely https://github.com/Martchus/cpp-utilities/blob/5425488421e6b27d81bdd010dcd0bc2655f7dc63/application/commandlineutils.cpp#L144. So the code sends a return key in the end. It does that to tweak the behavior when using `cmd.exe` and I suppose it makes everything worse in your terminal.

> There are other command-line solutions using ffmpeg, but that rewrites the entire mp3 file, and i am NOT going to rewrite my entire mp3 collection without also testing my entire mp3 collection (which is impossible, basically).

Rewriting is actually the safest solution. When using a tag editor (this one or any other tool) then rewriting can *often* (not always) be avoided but this has disadvantages, see https://github.com/Martchus/tageditor#backuptemporary-files. Note that rewriting doesn't mean re-encoding (and using ffmpeg also doesn't mean re-encoding as it can just copy streams).

> There could be a bug that corrupts the audio part that i don';t know about until years later when i listen to some song i lnever listen to. Do not want!! :)

I usually check whether recently updated audio files still work manually. However, sometimes I also do mass video re-encodings using some scripts which is similar to your use-case. The scripts are using MediaInfo to compare the length and track count of the original with the new file. I also use the Tag Editor to validate the file structure but this is normally only useful for Matroska/MP4 files. It is also useful to run ffprobe on the new file and grep for warnings/errors. Only if everything looks good after checking with these tools the original files are removed. Of course you could also try to compute a fingerprint of the audio stream using some tool. I haven't done that yet and would be curious myself whether this could be done with e.g. ffmpeg.

---

Note that Windows users normally use the GUI anyways so I haven't spent much effort into improving this especially because I'm using MSYS2 myself.

---

So, did it work to set the cover? I mean, did it work despite the error message? If it is actually working then the error message is just about ID3v1 and you can ignore it.

**Comment by ClioCJS** [comment]
Oooh, that's very interesting about the terminal stuff!  I'm hoping it wouldn't break the situation of me telling TagRename multiple times in one script (ahem, .BAT file), but I don't think it would since i'm not back at the terminal until the script is finished.

And, thanks for the update about tag writers rewriting the file. I guess.... I'm just paranoid about vague anxieties like "What if ffmpeg somehow doesn't reproduce the structure faithfully".

But I've now examined the 5 files I created using the method above, and i did get some interesting results:

```
manually adding with mp3tag simply adds this 1 tag as 2nd-to-last id3v1.1:
    TXXX: [Acoustid Fingerprint]: AQADtNIiSZSHicxRI3niI9sYlBWaWIqxH3{etc}  #original 2nd to last tag    
    APIC: []{3=Cover (front)}: image/jpeg, 116850 bytes                    #added by manually dragging in cover art in mp3tag
    PRIV: (unimplemented)                                                  #original last tag

eye3d - adds APIC: []{3-cover(front) to id3v2.3 tag as first tag
   APIC: []{3=Cover (front)}: image/jpeg, 116850 bytes   
   PRIV: (unimplemented)

TagEditor long syntax adds this at very end (but no PRIV after)
   APIC: [front cover]{3=Cover (front)}: image/jpeg, 116850 bytes

TagEditor short syntax adds this at very end  (but no PRIV after)
   APIC: []{0=Other}: image/jpeg, 116850 bytes







```

**Comment by ClioCJS** [comment]
So, while the problem of "mp3tag doesn't see tags inserted by tageditor or eye3d" is mp3tag's problem (and my problem, haha), it does see like the reason mp3tag can't see the tags is the lack of the "PRIV: (unimplemented)" at the end. That seems to be the main difference between the 3 ways of adding cover art (mp3tag manual drag, eye3d add, tageditor syntaxes)

Is it possible that there is a TagEditor syntax that would also let me put that PRIV tag in? I need to read the docs again. :)

**Comment by Martchus** [comment]
So it looks like setting the cover worked. I'll nevertheless improve the situation with the misleading error message when I have the time.

You should be able to set the "PRIV" field as a custom field. There's an example in the README (although not for this exact field). Supplying a valid value might be a bit cumbersome as you will need to pass a null-byte to terminate the owner identifier and possibly pass further binary data. Out of curiosity, what kind of data do you need to specify that doesn't fit in any of the normal fields?

**Comment by ClioCJS** [comment]
It does indeed work -- it's viewable in winamp and vlcplayer, which is good enough!  I'm just personally irked at mp3tag for not being able to "see" these tags, and only being able to see the ones they add themselves.  That's kind of myopic on mp3tag's part, and I think they would benefit from having someone as proactive as you on their team.

**Comment by ClioCJS** [comment]
Okay, so I am looking at the docs and it looks like wht I need to do is to simply add:

`id3:PRIV=SOMETHING
`
to the end of my current command line invocation of tageditor.exe

But you are right in that I don't know how to make that something be null.  
My guesses for that value would be "null" "(null)" "(unimplemented)" "\0" "None" or just "" putting nothing after the colon .... I know we've deviated off topic at this point, but any suggestion to what I might want to try to achieve that?

**Comment by ClioCJS** [comment]
And oh, to answer your question of "what kind of data do you need to specify that doesn't fit in any of the normal fields?", it's simply that I want to try to make the tags TagEditor puts in resemble the ones mp3tag does, so that I can review them in mp3tag out of my own need for excessive diligence at that step in my audio-intake process 😅  So nothing except that "PRIV" tag, really, because that's how mp3tag does things.

Ironically, I have an mp3tag bug to report now... Lol! :) I'm going to let them know they aren't correctly displaying the cover art!

**Comment by Martchus** [comment]
I think mp3tag is mainly targeting casual users and may have its simplifications/limitations which is fine. My tool on the other hand is written for people who are really interested in how multi-media files are structured like myself. So it has features like showing element trees of MP4 files that likely not so many people really need. On the other hand it has definitely rough edges as I only have a certain focus and can only put a limited amount of effort into it.

> But you are right in that I don't know how to make that something be null.

There's no special syntax for this in Tag Editor. I guess you would simply literally pass a null byte. How that is done really depends on the shell. There's also the `field>=path` syntax to read from a file. You likely need quoting so your shell passes the `>` literally.

> And oh, to answer your question of "what kind of data do you need to specify that doesn't fit in any of the normal fields?", it's simply that I want to try to make the tags TagEditor puts in resemble the ones mp3tag does, so that I can review them in mp3tag

I wouldn't bet that adding the PRIV tag makes the cover show up in mp3tag. Maybe it can only show certain cover types and the front cover isn't one of them? Of course this might also be a bug in my Tag Editor which might not serialize the cover in a 100 % standard conform way (but I wouldn't assume that without further evidence).

---

Since you were wondering about the order of fields: The tag editor always orders them [this way](https://github.com/Martchus/tagparser/blob/7d9d5c8408ca124421885a3574313031805e382a/id3/id3v2tag.cpp#L634) which should be based on a recommendation of the ID3v2 standard.

**Comment by ClioCJS** [comment]
TagEditor.exe really is most excellent!

**Comment by ClioCJS** [comment]
mp3tag actually handles all kinds of cover types, often giving an arrow to cycle through them, even allowing multiple of the same time. but clearly it has its own limitations in how it reads that cover.  

I used metamp3 to produce the tag information to compare the different outputs. My theory is that if i can make it look like what mp3tag makes it look like, then it would be readable in mp3tag.

I'd rather mp3tag fix their code, though, but I can't rely on that.

**Comment by ClioCJS** [comment]
And yea, based on what you said, I don't know that sending that null byte is something I can easily achieve.  I sure wish we could just say "=null" at the command line and have it substitute the null character itself there.

**Comment by ClioCJS** [comment]
Anyway, thank you for all the help!

I guess it appears the only bug on TagEditor's part is the false error message.

What a fun mystery to solve.

**Comment by Martchus** [comment]
The error message will be suppressed in the next release (https://github.com/Martchus/tageditor/commit/0e36eec6c76084fca1b6fc560abe5b29bd585502). Note that it isn't completely false, though. It is about the ID3v1 tag which indeed does not support a cover. In cases the message won't be suppressed it will now state the tag it is about.

**Comment by fheidenreich** [comment]
Just wanted to give a quick update here regarding the various mentions of Mp3tag in this issue: it's reading the covers fine.

The files @ClioCJS is referring to also have an APEv2 tag without cover art, which is preferred over ID3v2 if reading of APEv2 is enabled under **Options → Tags → Mpeg** (which is off by default).

**Comment by Martchus** [comment]
Thanks for the info. This tag editor doesn't support APE but tries hard to preserve everything unsupported/unknown when saving in general (to avoid data loss). So this it makes sense that this happens. I suppose this is not a fault of any of the tools then - although it is not ideal that users can easily get confused about it.

Note that I've never seen the point in implementing APE tags because ID3v2 is just sufficient for my use cases. Maybe it would nevertheless make sense to at least detect it and add a warning or info message in this case.

**Comment by Martchus** [comment]
Feel free to share a link to the Mp3tag-side of the discussion.

**Comment by fheidenreich** [comment]
> Feel free to share a link to the Mp3tag-side of the discussion.

This was via private email unfortunately.

> Note that I've never seen the point in implementing APE tags because ID3v2 is just sufficient for my use cases.

Yes, ID3v2 is sufficient in most (if not all) cases. APEv2 support in Mp3tag is a relict from a time where ID3v2 was in its infancy and not very well supported. foobar2000 had support for APEv2 and I've added this for compatibility reasons.

> Maybe it would nevertheless make sense to at least detect it and add a warning or info message in this case.

Mp3tag has a **Tag** column in the File List which lists all available tag types in a file along the one which is displayed, e.g., 
**ID3v2.3 (ID3v1 ID3v2.3 APEv2)**. This column makes use of the [information placeholders](https://docs.mp3tag.de/format/#technical-information) `%_tag_read%` and `%_tag%` (which are also available to the [Filter](https://docs.mp3tag.de/filter/) to, e.g., identify files with certain tag types).

**Comment by Martchus** [comment]
> Maybe it would nevertheless make sense to at least detect it and add a warning or info message in this case.

I was talking about making an improvement to *this* tag editor. I would have been surprised if Mp3tag had no way of showing the tag format :-)

**Comment by fheidenreich** [comment]
Yes, I was merely adding this bit of information as kind of inspiration on how other programs are dealing with this.

**Comment by Martchus** [comment]
Since I don't plan to implement APE support I've just implemented a warning if one is present. Maybe I'll implement it later at some point. As mentioned before, the misleading error is now suppressed. The question about the command line usage should be answered as well. So I guess this issue can be closed.

The CLI problem under Windows is something I'll try to figure out in a broader score anyway. Likely I'll end up creating a wrapper for the CLI. I've already tried a little bit harder to improve my current hack but it seems like this is just not going to work very well under Windows.

**Comment by Martchus** [comment]
@ClioCJS The next version of tag editor will have `tageditor-cli.exe` alongside `tageditor.exe`. This should fix the weird terminal behavior. At least in Mintty, Konsole, Windows Terminal and `cmd.exe` this wrapper-approach seems to work fine. Maybe you'd like to test it in your terminal as well. You can find binaries on my [build server's repository](https://martchus.no-ip.biz/repo/arch/ownstuff-experimental/os/x86_64) (use the static binaries).

**Comment by ClaireCJS** [comment]
I really love the approach of releasing a separate CLI tool! Bravo and thank you!
