### ISSUE TITLE
Writing application settings

### ISSUE THREAD

**Issue by MatthewAllan93** [Martchus/tageditor#108]
Hi, could it be possible to have an option in the settings. So that the original writing application is in the metadata of the file that is being edited instead of the program's name. Thanks.

**Comment by Martchus** [comment]
Yes, I guess that would be easy to implement (but not without a change in the underlying tagparser library).

Just to clarify: I assume this is about Matroska - because in any other formats such kind of meta-data is not touched anyways. Note that Matroska has actually muxing application and writing application. I assume it makes sense to allow keeping the writing application as-is in the tagparser library and expose that option via tag editor. Likely the same should be possible for the muxing application as well.

Note that editing tags of Matroska files means touching many parts of the files because often offsets and element sizes are changing. The tag editor also allows restructuring files, e.g. to include padding and to move the tag and/or index to the front. So this is close to actually remuxing the file and thus changing the writing library and application still seems like a sensible default.

**Comment by Martchus** [comment]
Implemented on master. Do you want a development build for Windows or GNU/Linux to test it out?
