### ISSUE TITLE
Proper version info with builds

### ISSUE THREAD

**Issue by svnpenn** [Martchus/tageditor#13]
All builds should list the proper version. Currently the last 4 devel builds are
showing the same version:

~~~
devel-5
Tag Editor, version 2.1.0

devel-4
Tag Editor, version 2.1.0

devel-3
Tag Editor, version 2.1.0

devel-2
Tag Editor, version 2.1.0
~~~

this makes troubleshooting harder than it needs to be. You can disambiguate
versions by using Git or similar:

~~~
$ git describe --tags
v2.0.0-15-g4cacaff
~~~

**Comment by Martchus** [comment]
I could add the Git revision and latest commit ID.

However, also the version of c++utilities, tagparser and other dependencies matters so I would have to include those versions also for this to be actually useful. I would also have to distinguish between version present at compile/link time and version present at runtime (because I usually *don't* link statically). So this is a little bit more complicated.

Maybe I'll implement it but it hasn't a high priority.

**Comment by svnpenn** [comment]
I dont think including the library version numbers is as important, but if you
must include them you could do it like this:

~~~
$ ffmpeg
ffmpeg version git-2015-05-03-29ef54a Copyright (c) 2000-2015 the FFmpeg developers
  built with gcc 4.9.2 (GCC)
  configuration: --enable-libx264 --enable-libfdk-aac --extra-ldflags=-static
  --cross-prefix=x86_64-w64-mingw32- --target-os=mingw32 --arch=x86_64
  --enable-gpl --enable-nonfree --logfile=/dev/stdout --disable-doc
  libavutil      54. 23.101 / 54. 23.101
  libavcodec     56. 35.101 / 56. 35.101
  libavformat    56. 31.100 / 56. 31.100
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 16.100 /  5. 16.100
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  1.100 /  1.  1.100
  libpostproc    53.  3.100 / 53.  3.100
~~~

**Comment by Martchus** [comment]
Implemented in https://github.com/Martchus/cpp-utilities/commit/412e7253090e5408a5621fa6f1f3d302f7860997

To apply this change, you must also rebuild tagparser and tageditor.

> I dont think including the library version numbers is as important

The version of c++utilities and tagparser are very important since  these libs developed very closely and often contain the source of the issues. Also the Qt version might be relevant.

So it looks like this now:
```
Tag Editor, version 2.2.2-289.900eb45
Linked against: C++ Utilities: 4.7.0-269.412e725, Qt Utilities: 5.6.1-163.6078f12, Tag Parser: 6.2.2-222.9a94d54, Qt Script: 5.8.0, Qt WebKitWidgets: 5.602.3, Qt Core: 5.8.0, Qt Concurrent: 5.8.0, Qt Network: 5.8.0, Qt Widgets: 5.8.0
```

Note that the displayed version is only the version which was present at link time and not necessarily the version present at runtime. But as far as I remember you only link statically so it makes no difference for you anyways.

**Comment by svnpenn** [comment]
@Martchus few things:

1. I had to add OpenSSL to get TagParser building:

   http://github.com/svnpenn/glade/blob/6f3e3f1/tagparser/makefile#L5

   No mention of that:

   http://github.com/Martchus/tagparser/search?q=openssl

2. Dont make tageditor-2.2.2-289.900eb45.exe, then make a symlink tageditor.exe,
just dont do that. No project I know does that outside of libraries. If someone
wants the version in the filename, they can symlink it the other way.

3. My build is not showing library versions:

       $ tageditor --help
       Tag Editor, version 2.2.2-289.900eb45

**Comment by Martchus** [comment]
1. OpenSSL is only for testsuite. I'll document it later and make it optional. 
2. That was not intended, will fix it.
3. I guess I know why. Cmake seems to make it a little bit harder than I thought by not exporting my custom target properties.

**Comment by Martchus** [comment]
The remaining problems should be fixed now. You need to rebuild everything to test.

**Comment by svnpenn** [comment]
still does not work without OpenSSL

**Comment by Martchus** [comment]
But other points are fixed? Then I would track the OpenSSL problem in [another issue](https://github.com/Martchus/tagparser/issues/2).

**Comment by svnpenn** [comment]
other now resolved. 1 nitpick - library version should be on separate lines like FFmpeg. not strictly required, but it looks nicer and is easier to parse if someone wanted to do that

**Comment by Martchus** [comment]
I decided to put everything in one line to save some space. Since the information isn't used so often I can live with a little bit worse readability. But maybe I can add `--build-info` to show detailed information in a more readable way similar to ffmpeg.

**Comment by svnpenn** [comment]
Closing since this is now fixed, thanks
