### ISSUE TITLE
Stop using ANSI escape codes with Windows

### ISSUE THREAD

**Issue by svnpenn** [Martchus/tageditor#24]
While it is true that certain Windows 10 versions do support this:

http://wikipedia.org/wiki/ANSI_escape_code#Windows_and_DOS

No other Windows version supports this, including the popular Windows 7. So you
end up with this:

~~~
$ tageditor --help
[1mTag Editor, version 2.2.5-330.df6c923
[0mLinked against: C++ Utilities: 4.10.0-392.784f3d9,
  Tag Parser: 6.5.0-332.d717913

[0mAvailable arguments:
[1m--qt-widgets-gui [0m
  shows a Qt widgets based graphical user interface (the application has not
  been built with Qt widgets support)
    [1m--file, -f [0m [path]
      specifies the path of the file to be opened
    [1m--renaming-utility [0m
      launches the renaming utility instead of the main GUI
~~~

**Comment by Martchus** [comment]
Ok - I only tested this with non-standard terminal under Windows.

I intend to add a `--no-color` option which will turn formatting off anyways. This will also be controllable by environment variable then. I'm currently a little bit busy, but this feature should make it into the next release.

I will not stop using ANSI escape codes with Windows in general because it works quite well if you use a decent terminal and apparently even in the Windows 10 standard terminal.

If you like to use the latest version from master and want to get rid of the formatting immediately, there are currently 2 workarounds:
* Invoke tageditor via a wrapper or Bash alias: `tageditor --help | sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g"`
* Wipe all formatting code in https://github.com/Martchus/cpp-utilities/blob/master/io/ansiescapecodes.h and https://github.com/Martchus/cpp-utilities/blob/master/io/ansiescapecodes.cpp. Then recompile everything (required because some functions might be inlined). When using `#ifdef` instead of just removing the code, this could even be an upstream commit.

**Comment by svnpenn** [comment]
Good comment - I think I will turn this into a pull request, if only for my own
convenience

However I think it is important to drop ANSI escape codes, at least for Windows. 
Notice carefully that Windows has its own way of doing this:

http://docs.microsoft.com/windows/console/setconsoletextattribute

Example:

http://github.com/FFmpeg/FFmpeg/blob/0655810/libavutil/log.c#L163-L167

So you saying "just use a better console", respectfully, is kind of the lazy
answer, rather than the portable one.

**Comment by Martchus** [comment]
In fact I wasn't aware of the Windows-way to do formatted output. I agree that this would be the preferable way under Windows then.

However, I'm not going to take that extra effort (of course such a contribution would be welcome) because making the formatting optional should be sufficient.

**Comment by Martchus** [comment]
This should be fixed by https://github.com/Martchus/cpp-utilities/commit/9829dbe7275dd665bd4b8e5c624c1b596d7bda79.

You can also disable formatting by default at compile time using [`ENABLE_ESCAPE_CODES_BY_DEAULT`](https://github.com/Martchus/cpp-utilities/blob/master/doc/buildvariables.md). So the behavior before introducing formatting can almost be restored. Note that this configure option relates to `c++utilities`, not the tag editor itself.

**Comment by svnpenn** [comment]
confirmed fixed - thanks
