### ISSUE TITLE
Compiling or Installing on Ubuntu?

### ISSUE THREAD

**Issue by TheVocaloidMiku64** [Martchus/tageditor#33]

**Comment by Martchus** [comment]
I can not provide packages for each and every Linux distribution out there. If you want a package for Ubuntu, you might ask the Ubuntu developers. Using the existing Arch Linux, Tumbleweed and Gentoo packages as base, this should be an easy task for someone experienced with Ubuntu's/Debian's package format.

Since I'm not even using Ubuntu or any Debian-based distribution myself I'm not going to work on this in the next time. Of course I'll keep this open since it is a valid feature request.

---

If you just want to compile it yourself (without packaging), just follow build instructions. Those are generic and should also work under Ubuntu. Especially the [building this straight](https://github.com/Martchus/tageditor#building-this-straight)-way should not be too hard.

Note that if you (or anybody else) who achieved compiling this under Ubuntu or any other platform, is welcome to share a platform-specific build script (eg. containing concrete package names for dependencies).

**Comment by Martchus** [comment]
If installing is sufficient, you could try the [AppImage](https://github.com/Martchus/tageditor/releases/download/v2.3.3/Tag.Editor-0-Build0.glibc2.14-x86_64.AppImage) I've added for the latest release.

**Comment by TheVocaloidMiku64** [comment]
Yeah, thanks. The AppImage version works for me. I'll try to get in touch with Ubuntu guys on how they can make a deb package for this app. Should you close this issue now?

**Comment by YoussofH** [comment]
Hi, I am also using a Debian OS I hope you have got an answer or a deb package, it would be nice if you share it with us. Thanks!

**Comment by Martchus** [comment]
I'm not aware that anybody took the effort to create a Debian package so far.

**Comment by siggy** [comment]
AppImage worked for me on Ubuntu 20.04 / WSL2. Thanks!

FWIW I had to install `libharfbuzz-dev` to get it working:
```bash
sudo apt-get update && sudo apt install libharfbuzz-dev
```

**Comment by Martchus** [comment]
Maybe you needed some dependency pulled in by the dev package but I wouldn't assume that the dev package itself is required.
