### ISSUE TITLE
m4a file is unseekable after adding cover image

### ISSUE THREAD

**Issue by chjcken** [Martchus/tageditor#40]
Hi there,

I'm trying some ways to add cover to my m4a (aac) files, and I found a solution lead to your project
https://askubuntu.com/a/849220 

My tageditor binary is built on Ubuntu 16.04 by myself after following the build instructions

I used tageditor cli to add cover image (see attachment for input files) 
[add_cover_unseekable.zip](https://github.com/Martchus/tageditor/files/2454696/add_cover_unseekable.zip)

> tageditor -s cover=cover.jpg --max-padding 100000 -f audio.m4a

I can play and seek the input file by any player but after adding cover, the result file play like normal  but stuck if I seek to another position on VLC or default Ubuntu media player (it is still playable and seekable by chrome and firefox browser)

Am I using wrong command or my tageditor built is broken?

If you need any other information, just tell me and please help me to make my audio is seekable and also has a cover.

Thank you in advance

**Comment by Martchus** [comment]
Thanks for the feedback and providing a sample file. I'll look into it later.

> Am I using wrong command

No command should break files - so no :-)

> my tageditor built is broken?

Indeed it would be useful to know which version/commit you're on. The version of tagparser is also important.

**Comment by chjcken** [comment]
Hi @Martchus ,

I just clone code from branch master for all projects needed to build tageditor: c++utilities, tagparser, tageditor

and I have just built tageditor last week so I think these projects on my PC are still latest update

**Comment by Martchus** [comment]
Unfortunately I can't reproduce the issue. I used your sample file and the exact command. Seeking still works with VLC and mpv.

mpv prints the warning:
```
[ffmpeg/demuxer] mov,mp4,m4a,3gp,3g2,mj2: stream 0, timescale not set
```
But that's just because it internally considers the cover a stream. So it is not a problem either. The warning also goes away when removing the cover again - so it is really just that.

Maybe you can also provide the damaged file?

**Comment by chjcken** [comment]
Hi @Martchus 

here is my damaged file 
[audio_unseekable.m4a.zip](https://github.com/Martchus/tageditor/files/2455779/audio_unseekable.m4a.zip)
hope you can take a look

By the way, the default media player I mentioned above is "totem"

> /usr/bin/totem

I just try to play the damaged file with vlc and seek, it show an error log like this

> [00007fd4b80009b8] core input error: INPUT_CONTROL_SET_POSITION(_OFFSET) 11.5% failed

And can you give me the output file that you have added cover and it is able to seek normally. Thank you

**Comment by Martchus** [comment]
Unfortunately totem plays none of the file on the Tumbleweed system I'm using right now (likely because underlying gstreamer libs are not built with support for AAC due to patent issues).

With VLC and other players I can play and seek the "unseekable" file you attached fine. (Using VLC 3.0.4 as provided by packman.)

> And can you give me the output file that you have added cover and it is able to seek normally.

It is identical to the "unseekable" file you have attached according.

---

I see 2 possibilities:  
1. There might be something wrong with the files, indeed. Even though some player can still handle it this is a bug in the tag editor which must be fixed.
2. The file is fine and some player are just not able to handle them correctly.

Not sure which of them is the case.

Does it work again if you use `tageditor -s cover= --max-padding 100000 -f audio.m4a` to remove the cover again. If yes, then 2. is quite likely. If not the file is actually damaged but I'm clueless in which way.

**Comment by chjcken** [comment]
Hi @Martchus 

I have tried remove cover as you said and unfortunately the output file after remove cover is not able to seek too,

I really have no idea about this case

I think maybe my audio file has problem before adding cover. I'm reviewing the encoding parameter.
If you find out anything, please tell me

Thank you for fast supporting and great projects.

**Comment by Martchus** [comment]
>  the output file after remove cover is not able to seek too

Ok, then the problem is the file being altered by the tag editor and not the presence of the cover. (That was more likely anyways.)

> I think maybe my audio file has problem before adding cover.

Too me - with the players I tested - it looks like there's no problem at all with the file. I also briefly checked the MP4 file's structure and couldn't see any obvious problems. That file is using multiple `moof`/`mdat` atoms but not `stco`/`co64` atom. This is a little bit special indeed, but I actually took care that the tag editor can handle those files as well.

> I'm reviewing the encoding parameter.

I would recommend not to use multiple `moof`/`mdat` atoms and just use an ordinary structured MP4 file instead. The `moof`/`mdat` structure is meant for streaming and not so much for your local music library. I'm also wondering why your file's document type isn't [DASH](https://en.wikipedia.org/wiki/Dynamic_Adaptive_Streaming_over_HTTP) because the use of multiple `moof`/`mdat` atoms seems to be special to that document type.

---

So my suspicion is that the code in the tagparser library to handle `moof` atoms is not correct but most players don't care and don't even print a warning. Maybe it is also just the (possible outdated version of) the player you're using.
