### ISSUE TITLE
Windows-specific console handling doesn't work correctly

### ISSUE THREAD

**Issue by bcurran3** [Martchus/tageditor#41]
When I type tageditor --help a new window appears, all the options scroll by super fast and then the window closes. There's no way to read the output.

**Comment by Martchus** [comment]
Which Windows version? I'll have a look under my Windows 10 installation when I have to boot it anyways.

See https://github.com/Martchus/tageditor/issues/15#issuecomment-269398504 for my recommendations under Windows (basically, use the MSYS2 terminal).

**Comment by bcurran3** [comment]
Win10 versions 1803 and 1809.

I want to use tageditor in some scripts to change metadata. Anyway you could post (or point me to) the command line options?

**Comment by bcurran3** [comment]
I just went and looked at the docs again. :)

tageditor get title
tageditor info

All output to a new window, scroll fast, and exit. Can't read anything.

**Comment by Martchus** [comment]
That get, info and basically any command is affected by this issue is no surprise.

I haven't looked into the issue so far but still I'd recommend to use the MSYS2 terminal if you have to use Windows.

Btw, the problem is that the same executable provides both - a CLI and a GUI. Having the terminal when using the CLI and not having it when showing the GUI requires some extra <s>effort</s>hacks under Windows. Likely that hacks don't work anymore as intended or haven't worked in some cases at all. I assume you're using the regular `cmd.exe`?

**Comment by bcurran3** [comment]
cmd, powershell, and take command, not familar with msys2

**Comment by Martchus** [comment]
Just from the looks of it I'd say powershell uses the same underlying terminal emulator than `cmd.exe`. I'm currently trying to improve the situation at least a little bit: https://github.com/Martchus/tageditor/issues/65#issuecomment-850505244
