### ISSUE TITLE
(3.1.2) tageditor CLI option --files ignores *.ext

### ISSUE THREAD

**Issue by bcurran3** [Martchus/tageditor#42]
Running tageditor and specifying --files filename1.mp4 filename2.mp4 works.

Running tageditor and specifying --files *.mp4 results in nothing, just returns to the command prompt.

**Comment by Martchus** [comment]
Quote from `README.md`:

> Here are some **Bash** examples which illustrate getting and setting tag information:

So the examples (using possibly shell specific syntax) might not work in other shells. I haven't really used `cmd.exe` for ages and I don't know in which way it handles globbing.

Note that for the tag editor both invocations should look like the first one. That is because the shell is supposed to handle the globbing, not the tag editor. If you actually pass `*.mp4` without letting the shell expand the glob expression (e.g. by using quotes in Bash) you should get an error message that the file `*.mp4` can not be opened.

**Comment by bcurran3** [comment]
I'm was going off the CLI examples. I understand it's stated as used in Bash. I had a reasonable expectation that *.MP4 filespec would work in Windows Command Prompt too. 

Easy enough to work around in scripts though.

Vagrant box for Windows testing? :)

> Examples
> Here are some Bash examples which illustrate getting and setting tag information:
> 
> Reading tags
> Displays title, album and artist of all *.m4a files in the specified directory:
> 
> tageditor get title album artist --files /some/dir/*.m4a
> Displays all supported fields of all *.mkv files in the specified directory:
> 
> tageditor get --files /some/dir/*.mkv
> Displays technical information about all *.m4a files in the specified directory:
> 
> tageditor info --files /some/dir/*.m4a

**Comment by Martchus** [comment]
> Not tagged as bug?

Not sure whether it is a bug. So far it looks more like a limitation of a certain shell.

> Sorry, I'm just starting to get that tageditor is Linux 1st and Windows 2nd. :)

This project is only developed by me and of course I have a certain focus. Contributions regarding other platforms than Linux are welcome of course.

Note that it is possible to install Bash (and likely other shells) under Windows. Maybe the "Windows-only" tag should rather be "`cmd.exe`-only". That's likely true for all outstanding "Windows-only" issues.
