### ISSUE TITLE
Cannot write id3 tags under windows.

### ISSUE THREAD

**Issue by dystopia2017** [Martchus/tageditor#46]
These are my attempted commands
tageditor tag=id3v1 set title="%title%" -f %work%\%mpd%\%mtrack%)
tageditor set id3v1:title="%title%" -f %work%\%mpd%\%mtrack%)
tageditor set id3v1:title=%title% -f %work%\%mpd%\%mtrack%)
tageditor set title="%title%" -f %work%\%mpd%\%mtrack%)

And this is the output

←[1;31mError: ←[0m←[1mUnable to parse arguments: ←[0mThe argument "set" can not be combined with "qt-widgets-gui".
See --help for available commands.

←[1;31mError: ←[0m←[1mThe field denotation "id3v1:title" could not be parsed: generic field name is unknown←[0m

←[1;31mError: ←[0m←[1mThe field denotation "id3v1:title" could not be parsed: generic field name is unknown←[0m

←[1mSetting tag information for "R:\_Test_\Test_Artist-Test_Album-VLS\01-artist-track.mp3)" ...←[0m
 - ←[1;31mError: ←[0m←[1mAn IO failure occured when reading/writing the file "R:\_Test_\Test_Artist-Test_Album-VLS\01-artist-track.mp3)".←[0m

The file isnt currently loaded, so I don't understand the read/write error also the --help does not work under windows and you can not redirect it to a text file to read. "tageditor --help>>help.txt" just sends the output to the shell not help.txt :(

**Comment by Martchus** [comment]
```
tageditor tag=id3v1 set title="%title%" -f %work%%mpd%%mtrack%)
```

This is wrong. Since `tag=id3v1` makes no sense for the argument parser without context it is assumed to be a filename you want to show in the GUI. Hence `qt-widgets-gui` is implied and you get the strange error message.

```
tageditor set id3v1:title="%title%" -f %work%%mpd%%mtrack%)
tageditor set id3v1:title=%title% -f %work%%mpd%%mtrack%)
```

The colon `:` syntax is simply not supported. Check the documentation for targeting specific tag formats. But that is likely not required at all in your case.

The last attempt might work but judging by the error message the passed file path is simply incorrect. The error message is quite unspecific but it at least tells you the path it tries to use (`R:_Test_\Test_Artist-Test_Album-VLS\01-artist-track.mp3`) and that is likely not correct because there's no colon after the drive letter.

> also the --help does not work under windows

see https://github.com/Martchus/tageditor/issues/41

**Comment by dystopia2017** [comment]
Thank you for your fast response. Yes my path was messed up :( it is setting id3v2 tags now by default but I still cannot get it to set v1 tags, here is an example with tag= move to after set

`%Apps%\tageditor set tag=id3v1 title="%title%" -f `%work%\%mpd%\%mtrack%`
 
and the output is. 

`←[1mSetting tag information for "R:\_Test_\Test_Artist-Test_Album-VLS\01-artist-track.mp3" ...←[0m
 - [100%] Updating ID3v2 tags ...
 - [100%] Preparing streams for updating ...
 - [100%] Writing ID3v2 tag ...
 - Changes have been applied.`

**Comment by Martchus** [comment]
use  
```
tageditor set --id3v1-usage always --id3v2-usage always ...
```

Note that `tag=id3v1` is only for specifying to which tag formats the subsequent parameters should go (default is to all) but not for specifying which tag formats should be generally used.

**Comment by dystopia2017** [comment]
Thank you very much for your help and your excellent program. You solved all my issued :)
