### ISSUE TITLE
Windows binary is pkg file - won't run - no dl link for Windows binary

### ISSUE THREAD

**Issue by turnkit** [Martchus/tageditor#47]

**Comment by Martchus** [comment]
https://en.wikipedia.org/wiki/Archive_file

**Comment by turnkit** [comment]
7zip won't decompress.  No one will run this version b/c there's no simple way to unarchive this archive.

**Comment by turnkit** [comment]
why not use an archive format that windows users are familiar with like zip?

**Comment by Martchus** [comment]
I actually plan to do this because I need to update my deployment/upload scripts anyways due to changes in my packaging structure.

So far I've just uploaded the raw archive produced by my build scripts for simplicity on my side. Note that it is not true that 7zip won't decompress. For me it works - the only annoyance is that you have to decompress and unpackage in 2 steps.

**Comment by turnkit** [comment]
I sure thought it should, but it did the .xz just fine, then he .tar just fine, then when I had a .pkg file there was nothing I could do with it.  Right clicking with z7ip no longer had a uncompress type option.  I guess I'm just saying you're losing a lot of people who'd use the app if they had a simple way to run it. Compiling it, or requiring a nonstandard windows archiver app will lose probably 65% of your potential user base.

**Comment by Martchus** [comment]
Updated my release script. The latest release uses ZIP and separate archives for the architectures.
