### ISSUE TITLE
Year not being set?

### ISSUE THREAD

**Issue by communistkiro** [Martchus/tageditor#54]
I recently install the pkg provided for Void after noticing it- it was wonderful. Before I'd used the following script, here `${z}` is the name of an mp3 with a path. I download mp3s with all the relevant metadata inside the name and use parameter expansion to get each field.

```
mp3info2 \
  -C id3v2_fix_encoding_on_write=1 -u2R \
  -C write_v24=1 \
  -t ${${z##* \#[0-9](#c1,) \([0-9](#c8)\)\] }%.mp3} \
  -a ${${${z##*/}% \[*?(\[*\]) \#[0-9](#c1,) \([0-9](#c8)\)\]*}#*/} \
  -l ${${z/*([*])* \[/}/ \#[0-9](#c1,) \([0-9](#c8)\)\]*} \
  -y ${(M)z/* \((#b)([0-9](#c4))(#b)([0-9](#c2))(#b)([0-9](#c2))\)\] */${match[1]}-${match[2]}-${match[3]}} \
  -n ${(M)z/* \#(#b)([0-9](#c1,)) \([0-9](#c8)\)\] */${match[1]}} \
  -g "$(cat /tmp/x)" \
  -F TPE2=%a \
  ${z};
```

I uncommented it and added this 
```
tageditor set \
  --id3v2-version=4 \
  --encoding=utf8 \
  --values \
  title=${${z##* \#[0-9](#c1,) \([0-9](#c8)\)\] }%.mp3} \
  artist=${${${z##*/}% \[*?(\[*\]) \#[0-9](#c1,) \([0-9](#c8)\)\]*}#*/} \
  album=${${z/*([*])* \[/}/ \#[0-9](#c1,) \([0-9](#c8)\)\]*} \
  year=${(M)z/* \((#b)([0-9](#c4))(#b)([0-9](#c2))(#b)([0-9](#c2))\)\] */${match[1]}-${match[2]}-${match[3]}} \
  track=${(M)z/* \#(#b)([0-9](#c1,)) \([0-9](#c8)\)\] */${match[1]}} \
  genre="$(cat /tmp/x)" \
  albumartist=${${${z##*/}% \[*?(\[*\]) \#[0-9](#c1,) \([0-9](#c8)\)\]*}#*/} \
  --files ${z};
```
The latter doesn't work as expected for the year field. Testing with mp3info2, I can see the field having a value, but this doesn't show up in ncmpcpp, my music player. There is no error, it is being set, but not read. I thought maybe the field name could be different, like date, but nah. 

The opts are identical, so what's causing this?

**Comment by Martchus** [comment]
It could be a bug. When I remember the year is treated simply as a text field so there shouldn't be any difference to other text fields from my side. Can you please provide an actual invocation? E.g. use `echo tageditor ...` to print how it is called. And example file or at least some information about the file you have would be helpful as well (e.g. has it also an ID3v1 tag and is there an existing ID3v2 tag and if yes, which version).

Note that `year` is mapped to `TYER`. Maybe you just wanted to set the record date `TDRC` instead? That would be `recorddate` within the tag editor.

**Comment by Martchus** [comment]
The tag editor should handle this better. So far it is indeed inconsistent and sets `TYER` on an ID3v2.4.0 tag although it should be either `TDRC` or `TDRL`.

That's how I think it is supposed to work in the different formats:

1. ID3v2.3.0 has only `TYER` which is supposed to be the year of the recording. There's also `TDAT` and `TIME` for the record date and time. I guess the generic `recorddate` should go into these fields when using ID3v2.3.0.
2. ID3v2.4.0 has `TDRC` for the full recording timestamp. That's where `recorddate` should to into when this version is used. It also has `TDRL` which would be the *release* timestamp.
3. Matroska has `DATE_RECORDED` which should be mapped like `TDRC` and `DATE_RELEASED` which should be mapped like `TDRL`.
4. ID3v1 has a "year". It is unclear what it is supposed to mean exactly.
5. In MP4 "©day" is the "year". It is unclear what it is supposed to mean exactly.
6. In Vorbis comments there's `DATE` which is the recording timestamp and should be mapped like `TDRC`.

Seems like I should introduce `releasedate` for `TDRL` and support `recorddate` appropriately in ID3v2.3. I should remove the year from the from the "generic" fields because it is just unclear what it means (recording date vs. release data). Not sure where to map 4. and 5. to. Likely it is best to check what other tools do. I should also validate the format and maybe try to convert it if necessarily.

Does this make sense?

**Comment by communistkiro** [comment]
>  ID3v1 tag and is there an existing ID3v2 tag and if yes, which version).

Hm, this might have something to do with it, because bandcamp files are never blank slates. I know for sure that id3v1 via mp3info always cropped yyyy-mm-dd into yyyy.

Now, I should have specified, some filed **did indeed** get the proper date from the filename, which comes in a string `yyyymmdd`. Though with the batch I had, unless I messed up something- most were year only, and some had the full date. 
```
0 /tmp/lol |> mp3info -D *mp3 | gre 'Year' ; echo; echo; tageditor get year -f *mp3;
mp3info: invalid option -- 'D'
Album:   Energetic Bursts (Music for 17 Year:  2019
Album:   Energetic Bursts (Music for 17 Year:  2019


Tag information for "Aaron Myers-Brooks [Energetic Bursts (Music for 17-Tone Guitar) #1 (20190706)] Pressurized.mp3":
 - ID3v1 tag
    Year              2019
 - ID3v2 tag (version 2.3.0)
    Year              2019

Tag information for "Aaron Myers-Brooks [Energetic Bursts (Music for 17-Tone Guitar) #8 (20190706)] Chasm.mp3":
 - ID3v1 tag
    Year              2019
 - ID3v2 tag (version 2.3.0)
    Year              2019
```
The original year tag was implemented for copyright purposes way back when CD mp3 where still a thing; the release date and recording date make more sense from an archival or collection point of view, and they were only in later version, i think? Trying with recorddate, that i hadn't seen before, this is output: and now both are read as 2019 by ncmpcpp.
```
0 /tmp/lol |> tageditor set --values recorddate=2019-07-06 -f *mp3
Setting tag information for "Aaron Myers-Brooks [Energetic Bursts (Music for 17-Tone Guitar) #1 (20190706)] Pressurized.mp3" ...
 - [100%] Updating ID3v2 tags ...
 - [100%] Preparing streams for rewriting ...
 - [100%] Writing ID3v2 tag ...
 - [100%] Writing MPEG audio frames ...
 - [100%] Writing ID3v1 tag ...
 - Changes have been applied.
Setting tag information for "Aaron Myers-Brooks [Energetic Bursts (Music for 17-Tone Guitar) #8 (20190706)] Chasm.mp3" ...
 - [100%] Updating ID3v2 tags ...
 - [100%] Preparing streams for rewriting ...
 - [100%] Writing ID3v2 tag ...
 - [100%] Writing MPEG audio frames ...
 - [100%] Writing ID3v1 tag ...
 - Changes have been applied.
```
And ncmpcpp

**Comment by Martchus** [comment]
> `tageditor set --values recorddate=2019-07-06 -f *mp3`
> [...]
> and now both are read as 2019 by ncmpcpp

I'm afraid that's how one has to set it due to current limitations/simplifications within the tag editor. To summarize: You have to use `recorddate` for ID3v2.4.0 (and `year` only for ID3v2.3.0) and you'll have to take care of the formatting yourself.

> The original year tag was implemented for copyright purposes way back when CD mp3 where still a thing

That would make sense. But I still want to check how other (more popular) implementations do the mapping, e.g. taglib which also supports ID3 and MP4 at the same time.

**Comment by communistkiro** [comment]
Perhaps an option to removed fields from specific tag version before writing them. 
I tried with `--remove-target` and `--remove-other-fields` in a step before setting the recorddate field, but both failed to produce a difference.

**Comment by Martchus** [comment]
`--remove-target` is only relevant for Matroska. `--remove-other-fields` should actually remove e.g. a previously present `TYER` field.

But I plan to let the tag editor take care of it. So one would only use `recorddate` and `releasedate` anymore and it would work work with all formats supporting the fields and in particular all ID3v2 versions. If necessary it would remove old ID3v2.3.0 fields in favor of ID3v2.4.0 fields (or vice versa when converting an ID3v2.4.0 tag to ID3v2.3.0).

**Comment by Martchus** [comment]
I likely need to be some more testing but it should be implemented now.

An automatic conversion to the correct format (and a warning if that is not possible) is still missing.

**Comment by git-anish** [comment]
hey, 

getting this error when using releasedate="2021-05-06" or recorddate="2021-05-06" or year="2021-05-06". I even tried using --remove-other-fields before writing the new info to the file. Any specific reason this would be happening?


[1;31m[0m[1m    Error        [0m23:56:57   parsing ID3v2 tag: Unable to parse the full date of the recording. Only the 'Year' frame could be parsed; related frames failed: month is out of range

**Comment by Martchus** [comment]
I cannot reproduce this bug. Which version of c++utilities, tagparser and tageditor have you been testing with?
