### ISSUE TITLE
Little help with build please

### ISSUE THREAD

**Issue by FluffyDiscord** [Martchus/tageditor#63]
Hi, I am not familiar with cmake and the whole building process. I tried to build a version, but the cmake is unable to find package, The c++utilities thingy is git cloned there, but cmake still cant find it, any tips ? Or if possible, can you build it for me please ?

```
cmake -DCMAKE_BUILD_TYPE=Release \
-DWIDGETS_GUI=OFF -DQUICK_GUI=OFF \
 -DENABLE_JSON_EXPORT=ON \
 -CMAKE_MODULE_PATH="/home/user/tageditor/c++utilities" \
 -DCMAKE_INSTALL_PREFIX="/usr/bin/tageditor" \
 ~/tageditor
```

Build I am trying to make:
- debian (raspberry pi 4) compatible
- only cli
- json export

**Comment by Martchus** [comment]
The CMake command looks quite wrong, e.g. `-CMAKE_MODULE_PATH=…` is **not** how you make it find c++utilities. Since you're not familiar with CMake, just try to follow the [build instructions](https://github.com/Martchus/tageditor#building-this-straight) more closely. Of course you can keep the options `-DWIDGETS_GUI=OFF -DQUICK_GUI=OFF -DENABLE_JSON_EXPORT=ON` if you want to configure it that way. Be sure to install all dependencies mentioned in the README. Note that for the JSON export LLVM/Clang/libtooling is required and it may not be worth it since the JSON export feature is not very sophisticated anyways.
