### ISSUE TITLE
How to set unsyncedlyrics from a text file

### ISSUE THREAD

**Issue by aman-rohilla** [Martchus/tageditor#65]

**Comment by Martchus** [comment]
The syntax is `tageditor set 'lyrics>=/path/to/file.txt' -f foo.mp3` where the specified file is assumed to contain UTF-8 text (like CLI arguments are assumed to be UTF-8). The `>` after the field name indicates that the field value should be read from a file. Note that it is likely necessary to quote it in your shell.

But there's also bad news: I've never used this feature myself for ages and just found out that it is broken. I've just pushed [a fix](https://github.com/Martchus/tageditor/commit/53f0f02c72bb8f9cc4f9890a7a404600fb6d3e0c) so the latest Git master should now, though.

Note that with Bash and similar shells you can also just use `tageditor set lyrics="$(cat /path/to/file.txt)" -f foo.mp3` (instead of relying on special syntax from the tag editor itself).

**Comment by aman-rohilla** [comment]
Sir I am using windows and I found a similar command to cat in windows which is Get-Content for Powershell. But you should fix for windows version

**Comment by Martchus** [comment]
Like I said, I've already pushed a fix to the repository. Here's a development build for Windows if you want to help me testing: https://martchus.no-ip.biz/repo/arch/ownstuff-experimental/os/x86_64/mingw-w64-tageditor-qt6-3.3.11-1-any.pkg.tar.zst

**Comment by aman-rohilla** [comment]
I'm unable to extract. winrar says damage archive . I also tried to extract it online but sites said damaged or unsupported archive.

**Comment by Martchus** [comment]
The compression format being used here is zst. It is quite modern so the tools you've been using likely just don't support it. I've been extracting the archive for you on the server using `bsdtar xf mingw-w64-tageditor-qt6-3.3.11-1-any.pkg.tar.zst`: https://martchus.no-ip.biz/repo/arch/ownstuff-experimental/os/x86_64/usr/x86_64-w64-mingw32/bin/tageditor-qt6-static.exe

Note that you can install `bsdtar` and a better shell on Windows conveniently via MSYS2.

**Comment by aman-rohilla** [comment]
Wohooo, Yes it's working now. Thank very very much sir. I was googled for very long and I did not find a single command line tag editor which could write lyrics. Yours is the only one. Thank you very very much. One more thing, when I run the command for setting lyrics like tageditor set "lyrics>=lyrics.txt" -f song.m4a , it creates a new file song.m4a.bak and even after the command has run, this file don't get deleted by itself and size of song.m4a,bak if nearly similar to song.m4a. This way it will consume the storage of my pc because it's creating an extra file. Now I ask you,  can I delete song.m4a.bak.

**Comment by Martchus** [comment]
Yes, you can delete them afterwards if everything worked fine (see https://github.com/Martchus/tageditor#backuptemporary-files for further details).

I could add a quite flag which would suppress the progress log and any messages besides warnings and errors.

**Comment by aman-rohilla** [comment]
Thank you for all of your support

**Comment by Martchus** [comment]
No problem. Then I'm closing the issue. The next release will also have a quiet flag for the `set` operation.

**Comment by aman-rohilla** [comment]
Sir, one more request, I was trying to get tag fields by tageditor.exe get title -f song.m4a , but I couldn't make it to write to a file by tageditor.exe get title -f song.m4a > tags.txt Even _popen() [https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/popen-wpopen?view=msvc-160] failed to read the console output. I need this to change the filename of a song based on tag fields.

**Comment by Martchus** [comment]
I know that this is broken. However, only Window's default terminal emulator (`cmd.exe`) seems affected. It works on any other platform and also under Windows one can just use a better terminal emulator like mintty (e.g. via MSYS2).

Note that the mistake must be somewhere within this function: https://github.com/Martchus/cpp-utilities/blob/master/application/commandlineutils.cpp#L89  
However, since one can simply use mintty I haven't put any effort in fixing it so far. Btw, when I remember correctly, without this function there was no console output at all but maybe this kind of setup is obsolete now.

**Comment by Martchus** [comment]
Having an executable which is a console application and a GUI application at the same time seems really not easily possible under Windows, at least with `cmd.exe`.

As a minor improvement I'll make it possible to avoid attaching the process to the parents console (or even spawning a new one). Then no output will be visible within `cmd.exe`'s window but redirections should work as expected. I've been updating the development build under https://martchus.no-ip.biz/repo/arch/ownstuff-experimental/os/x86_64/usr/x86_64-w64-mingw32/bin/tageditor-qt6-static.exe. To test this, use `set ENABLE_CONSOLE=0` before launching the tag editor.

I'm also setting the console's encoding now to UTF-8 by default which seems to work much better now (compared to several years ago). One can disable it via `ENABLE_CP_UTF8=0` on older Windows versions (where it might do more harm than good). Note that stdout/stderr is always UTF-8. This switch just enables the console to actually treat stdout/stderr as UTF-8 but shouldn't affect redirections.

Note that in your use-case it likely also makes sense to pass `--no-color` or to set `ENABLE_ESCAPE_CODES=0`.

**Comment by aman-rohilla** [comment]
Sorry for replying late, I tried as you said. I ran set ENABLE_CONSOLE=0, and then I ran tageditor.exe set "title=tageditor" -f song.m4a --max-padding 102400 , Earlier with this command tageditor wasn't creating song.bak but now when ENABLE_CONSOLE=0 is set, it creates a song.bak.  The console output redirection to a file is working when ENABLE_CONSOLE=0 is set. Also these two flags '--no-color or to set ENABLE_ESCAPE_CODES=0', changed the console error color to white, means they are working. One more issue I got is 'The field denotation "wwwcopyright" could not be parsed: generic field name is unknown'. i.e. it's unable to find non-common tags like www, wwwcopyright, origalbum, wwwaudiosource, copyright. I have set them for purpose. But seems like tageditor is unable to print these values.

**Comment by Martchus** [comment]
How did you set them and how do you attempt to read them (which command lines did you use)? Note that `wwwcopyright` is not a valid field denotation in some tag formats, e.g. ID3v2/MP4. See the section about setting custom fields within README.md for details.

But it is likely that you're in fact hitting other limitation there anyways. Since the tag editor doesn't know the fields it doesn't know that their contents are actually printable text and the encoding being used could only be guessed. So it cannot reliably print them. The `extract` operation could be used instead of `get` to workaround this, though.

Note that at some point it might make more sense to use the underlying library [tagparser](https://github.com/Martchus/tagparser) directly (if you don't mind writting a bit of C++ code).

**Comment by aman-rohilla** [comment]
I used another software. If you would like to know the name. Kid3-cli and mp3tag.de can do this. Mp3tag is really powerful I have used it for years but It does not support cli. I could have used the library because I know c++ a little. But I couldn't set up any library in mingw. I fail everytime and end up doing system() calls. Maybe because things are not simply for windows.

**Comment by Martchus** [comment]
Then I can't tell what these fields look like in different tag formats they might appear.

It should generally be possible to build on Windows if all dependencies are installed and their versions are recent enough (CMake 3.19 is required on master). I compiled the library some time ago with the mingw-w64 environment from MSYS2 and it worked. Another user built this within a Cygwin environment. Note that Cygwin is generally *not* required; mingw-w64 with its pthreads library (and a libstdc++ utilizing it) are sufficient.
