### ISSUE TITLE
Crash while parsing flac

### ISSUE THREAD

**Issue by EwanGreen4** [Martchus/tageditor#68]
Editor recieves SIGABRT at line 855 of `tageditorwidget.cpp` in `TagEditorWidget::startParsing()` 
(`m_fileInfo.parseEverything(diag, progress);`)

```cpp
bool TagEditorWidget::startParsing(const QString &path, bool forceRefresh)
{

        ...

        try {
            // try to open with write access
            try {
                m_fileInfo.reopen(false);
            } catch (const std::ios_base::failure &) {
                // try to open read-only if opening with write access failed
                m_fileInfo.reopen(true);
            }
            AbortableProgressFeedback progress; // FIXME: actually use the progress object
            m_fileInfo.setForceFullParse(Settings::values().editor.forceFullParse);
            m_fileInfo.parseEverything(diag, progress);
            result = ParsingSuccessful;
        } catch (const Failure &) {
            // the file has been opened; parsing notifications will be shown in the info box
            result = FatalParsingError;
        } catch (const std::ios_base::failure &e) {
            // the file could not be opened because an IO error occurred
            m_fileInfo.close(); // ensure file is closed
            result = IoError;
            if ((ioError = QString::fromLocal8Bit(e.what())).isEmpty()) {
                ioError = tr("unknown error");
            }
        } catch (const std::exception &e) {
            diag.emplace_back(TagParser::DiagLevel::Critical, argsToString("Something completely unexpected happened: ", +e.what()), "parsing");
            result = FatalParsingError;
        }
 
        ...

}
```

Throws this error
```
/usr/include/c++/11.1.0/string_view:234: constexpr const value_type& std::basic_string_view<_CharT, _Traits>::operator[](std::basic_string_view<_CharT, _Traits>::size_type) const [with _CharT = char; _Traits = std::char_traits<char>; std::basic_string_view<_CharT, _Traits>::const_reference = const char&; std::basic_string_view<_CharT, _Traits>::size_type = long unsigned int]: Assertion '__pos < this->_M_len' failed.
Aborted (core dumped)
```

fre:ac, MusicBrainz Picard, and thunar-media-tags-plugin are all able to view the tags without such errors.

[This zip](https://drive.google.com/file/d/1Keu8Q40nizDvOjRQZirpV1k5xZhQ7t5V/view?usp=sharing) includes the file in question, as well as its .ogg counterpart (which is parsed without issue in tageditor)

**Comment by Martchus** [comment]
I cannot reproduce. Which version are you using exactly, which compile flags, which platform, which version of Qt?

**Comment by EwanGreen4** [comment]
The crash happens both from the AUR package (I assume that's the latest release) and the latest from about 2 hours ago.

The short of it; I'm not using any build flags specific to tageditor. I don't think other compile flags have much to do with it, either -- the behavior is the same between the AUR version (I don't know the flags that uses), the kit I'm using, and something simple like `cmake -B ./build -S ./ && cd ./build && make -j4`.

I am using Qt 5.12.2. I tried it with 6.0.2 while writing this response, and the behavior is the same.

I am using Arch Linux x86_64.

This is from the manual CMake build. The only difference between the AUR and Qt Creator builds are the timestamp and path.
`Sat 2021-07-03 16:42:44 MDT  378938 1000 1000 SIGABRT present  /home/ewan/tageditor/build/tageditor                                            4.5M`

**Comment by Martchus** [comment]
> I'm not using any build flags specific to tageditor. …

Your explanation isn't very convincing because the build system (CMake) picks up flags from the environment. When using `makepkg` the environment variables are populated from `/etc/makepkg.conf`. However, you don't actually need to retrace all places where  you possibly have specified build flags. Just run e.g. `make VERBOSE=1` to print the compiler invocations. Note that the build of tagparser (and possibly even c++utilities) might be interesting as well. (Following https://github.com/Martchus/tageditor#building-this-straight you can build all projects together in one go.)

> This is from the manual CMake build. The only difference between the AUR and Qt Creator builds are the timestamp and path.
> Sat 2021-07-03 16:42:44 MDT 378938 1000 1000 SIGABRT present /home/ewan/tageditor/build/tageditor 4.5M

I was asking for the coredump itself, so I can investigate the problem via GDB. Since it is reproducible within the "Qt Creator" version, please preferably send the coredump of the crash of this version as I assume you conducted a debug build within Qt Creator.

By the way, you could also cross-check with the binaries from my repository: https://martchus.no-ip.biz/repo/arch/ownstuff

---

Note that I wouldn't ask for that much but I cannot reproduce the issue here (with your same file).

**Comment by Martchus** [comment]
What was the resolution?

**Comment by EwanGreen4** [comment]
You being unable to reproduce the issue with all the information makes me think it's an issue on my end, a fault of a dependency that wouldn't be relevant to this repository or something of the like. I would be happy to reopen the issue if this is actually an important problem to you. 

Flags (everything from the `ARCHITECTURE, COMPILE FLAGS` section of makepkg.conf that isn't commented out):
```
CARCH="x86_64"
CHOST="x86_64-pc-linux-gnu"

CFLAGS="-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions \
        -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security \
        -fstack-clash-protection -fcf-protection"
CXXFLAGS="$CFLAGS -Wp,-D_GLIBCXX_ASSERTIONS"
LDFLAGS="-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now"

DEBUG_CFLAGS="-g -fvar-tracking-assignments"
DEBUG_CXXFLAGS="-g -fvar-tracking-assignments"
```
[Coredump](https://drive.google.com/file/d/1v1ZU6_hHesutwrBueV4enr-3BZflt3rp/view?usp=sharing)

I will try again with the full stack build and tell you my results.

**Comment by EwanGreen4** [comment]
Ahhhh.....

![image](https://user-images.githubusercontent.com/36348486/124401380-66c97680-dce6-11eb-8895-a68d2b06852e.png)

Okay, so it seems like what you though was right -- it's something up with tagparser. I should have seen this coming from the start, the issue was in the TagParser class, in a file in the tagparser folder, etc... I still don't know what the problem was exactly, but it works perfectly having just rebuilt it with the method in the readme. 

If it helps, I got tagparser from the AUR as well, along with c++utlities, qtutilities, and anything else I could to satisfy tageditor's dependencies. 

Maybe there is some problematic version difference going on there. Seeing as how my AUR manager script uses makepkg all the same, I think it's safe to say it was a problem with the code and not with the environment (build flags and such).

**Comment by Martchus** [comment]
Looks like the coredump is useless without the build. I guess it isn't worth investigating this further.

Maybe you installed the `-git` packages from the AUR. Then you might have been missing a rebuild of `tageditor-git` (after updating `tagparser-git`). The build conducted with Qt Creator might have been using a different version of the tagparser library at runtime than it had used at linktime. (The build instractions from the README are unproblematic because they use static libraries and build everything in one go to ensure consistency.)
