### ISSUE TITLE
Can't access USB drives

### ISSUE THREAD

**Issue by bigziw** [Martchus/tageditor#92]
![1](https://user-images.githubusercontent.com/69008910/196217229-3727f089-0dce-49c5-a2c2-67e7864aaee3.png)

**Comment by Martchus** [comment]
A little bit more info would help. Is that a screenshot of Tag Editor? If no, I assume the volume doesn't show up at all. If yes, what happens if you try to expand it? Can you select the file via the menu entry "File -> Open"? Are you using the official Windows builds and if yes, which build did you use exactly?

**Comment by Martchus** [comment]
It works on Windows 10 for me - but only when using the Qt 6 based version. Since the Qt 5 based version is only provided for using older Windows versions I suppose having this only working in the Qt 6 based version is good enough.
